### PR TITLE
generic error handling to avoid adapter crash in case of async issues

### PR DESCRIPTION
**Pull request by DutchmanNL**
code had quite some await request without try/catch, based on logging we expect parts of the code crash unexpectedly 

this PR adds generic error logging and try/catch to cover all scenarios. Error function ensure error and error.stack is provided to log message which will show in which part of the code the crash is caused

### CODE REVIEW

**Review by raintonr — CHANGES_REQUESTED** [review]
I'm sorry, but please don't reformat the whole file. When I see loads of formatting changes I specifically avoid doing that.

**Comment by DutchmanNL** [comment]
> I'm sorry, but please don't reformat the whole file. When I see loads of formatting changes I specifically avoid doing that.

I have to, you should I otherwise cover the ESLint checks ?

Adding try/catch requires to move the code inside that block by one space according to your ESLint settings

**Comment by DutchmanNL** [comment]
Solved ESLint error in testing

**Comment by raintonr** [comment]
Well... added a few in https://github.com/iobroker-community-adapters/ioBroker.acme/commit/e4d0903b6567b25da2af4bb7b08925aa6d3bb2ac so this PR outdated.

**Comment by DutchmanNL** [comment]
> Well... added a few in https://github.com/iobroker-community-adapters/ioBroker.acme/commit/e4d0903b6567b25da2af4bb7b08925aa6d3bb2ac so this PR outdated.

You still have a couple await not covered by an try catch, as suggested on telegram all await should be within an try/catch to have proper error handling

**Comment by raintonr** [comment]
Don't think so. Which lines?

**Comment by DutchmanNL** [comment]
> Don't think so. Which lines?

Like here 

https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L386

https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L388

https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L389

https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L390

https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L392

https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L441

**Comment by DutchmanNL** [comment]
Additional remark, you don't provide output of the error.stack as I advised and provided in my PR, that would give you more valuable information about the error

**Comment by raintonr** [comment]
> Like here
> 
> https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L386
> 
> https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L388
> 
> https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L389
> 
> https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L390
> 
> https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L392
> 
> https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L441

These are all in the `generateCollection` method which can only be called from L67 which itself is inside a try...catch.
 
> https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js#L295

Same for this as `stopAdaptersOnSamePort` is only called from within `generateCollection`

**Pull request closed without merging**
